(function () {
  "use strict";

  /** @type {{ en: Record<string, string>, es: Record<string, string> }} */
  const T = {
    en: {
      "meta.title": "Sentinella · Precision monitoring for mining tailings",
      "meta.description":
        "Real-time IoT for tailings dams: alerts, digital twin, regulatory reporting and offline-capable operations.",
      "skip": "Skip to content",
      "nav.start": "Start",
      "nav.features": "Features",
      "nav.benefits": "Benefits",
      "nav.pricing": "Pricing",
      "nav.contact": "Contact",
      "nav.requestDemo": "Request demo",
      "hero.title": "Streamline your workflow with our robust platform.",
      "hero.subtitle":
        "Optimize processes, reduce overhead, and scale operations seamlessly with an integrated toolset designed for modern teams.",
      "hero.ctaTrial": "Start free trial",
      "hero.ctaDocs": "View documentation",
      "hero.imgAlt":
        "Mining operations dashboard on a wide curved monitor: real-time sensor charts, map view of the tailings facility.",
      "stats.v1": "99.9%",
      "stats.l1": "Uptime SLA",
      "stats.v2": "10k+",
      "stats.l2": "Active users",
      "stats.v3": "$50M",
      "stats.l3": "Processed daily",
      "cap.title": "Core capabilities",
      "cap.subtitle":
        "Everything you need to manage your infrastructure, neatly organized in one unified dashboard.",
      "cap.1t": "Real-time monitoring",
      "cap.1d":
        "Build personalized views of your most critical metrics. Drag, drop, and configure widgets instantly.",
      "cap.2t": "Automatic alerts",
      "cap.2d":
        "Connect external tools securely with our RESTful endpoints and comprehensive webhooks.",
      "cap.3t": "Blockchain traceability",
      "cap.3d":
        "SOC2-compliant infrastructure with role-based access control and end-to-end encryption.",
      "cap.4t": "Executive dashboard",
      "cap.4d":
        "Monitor system performance and user behavior with millisecond-latency data streams.",
      "cap.5t": "Automatic regulatory reports",
      "cap.5d":
        "Set up complex if/then triggers to handle repetitive tasks without human intervention.",
      "cap.6t": "Mobile app for operators",
      "cap.6d":
        "Access our dedicated technical support team anytime via chat, email, or priority phone.",
      "flow.title": "Implementation flow",
      "flow.s1": "Step 1",
      "flow.d1": "Install IoT nodes in the tailings deposit",
      "flow.s2": "Step 2",
      "flow.d2": "The system detects anomalies in real time",
      "flow.s3": "Step 3",
      "flow.d3": "Receive automatic alerts via app or email",
      "flow.s4": "Step 4",
      "flow.d4": "Generate regulatory reports with one click",
      "roles.opTitle": "Tailings operators",
      "roles.op1": "Alerts in the field",
      "roles.op2": "Digital checklist",
      "roles.op3": "Offline app",
      "roles.op4": "Round traceability",
      "roles.mgrTitle": "Plant managers",
      "roles.mgr1": "Dashboard with KPIs",
      "roles.mgr2": "Alert history",
      "roles.mgr3": "Reports for audits",
      "roles.mgr4": "IoT node map",
      "price.title": "Transparent pricing",
      "price.subtitle": "Scale your usage without hidden fees.",
      "price.popular": "Most popular",
      "price.ecoName": "Economy",
      "price.ecoFirst": "$190",
      "price.ecoFirstNote": "1st month",
      "price.ecoRec": "$90/mo from the 2nd month",
      "price.ecoFeat": "5 devices (one-time) · $90 web + $100 IoT",
      "price.ecoBtn": "Select plan",
      "price.premName": "Premium",
      "price.premFirst": "$380",
      "price.premFirstNote": "1st month",
      "price.premRec": "$140/mo from the 2nd month",
      "price.premFeat": "12 devices (one-time) · $140 web + $240 IoT",
      "price.premBtn": "Select plan",
      "price.maxName": "Max",
      "price.maxFirst": "$620",
      "price.maxFirstNote": "1st month",
      "price.maxRec": "$220/mo from the 2nd month",
      "price.maxFeat": "20 devices (one-time) · $220 web + $400 IoT",
      "price.maxBtn": "Contact us",
      "test.t1": `Implementing this blueprint cut our deployment times in half. The structural clarity it brings to our stack is unmatched.`,
      "test.a1": "Sarah Jenkins — CTO, TechCorp",
      "test.t2": `The clean UI and data hierarchy meant almost zero training for our staff. A precise, effective tool.`,
      "test.a2": "David Chen — VP Ops, GlobalLogistics",
      "contact.title": "Request a demonstration",
      "contact.subtitle": "Fill out the form below and our sales team will contact you within 24 hours.",
      "contact.name": "Name",
      "contact.company": "Company",
      "contact.mail": "Email",
      "contact.msg": "Message",
      "contact.phName": "Jane Doe",
      "contact.phCo": "Acme Inc.",
      "contact.phMail": "jane@acme.com",
      "contact.phMsg": "Briefly describe your use case…",
      "contact.submit": "Submit request",
      "contact.feedbackWarn": "Enter a valid email, company name, and at least 12 characters in the message.",
      "contact.feedbackOk": "Your mail client will open with the request; review and send when ready.",
      "footer.copy": "© {year} Sentinella. All rights reserved.",
      "footer.tagline": "Precision monitoring for mining tailings",
      "footer.privacy": "Privacy policy",
      "footer.terms": "Terms of service",
      "legal.skip": "Skip to content",
      "legal.backHome": "Back to Sentinella",
      "legal.privacyDocTitle": "Privacy policy · Sentinella",
      "legal.termsDocTitle": "Terms of service · Sentinella",
      "toggle.open": "Open menu",
      "toggle.close": "Close menu",
    },
